# Generated by Django 4.1.3 on 2023-02-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadiscription',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
