# Generated by Django 4.1.3 on 2023-02-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0002_alter_datadiscription_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDiscriptionN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='DataDiscription',
        ),
    ]
