# Generated by Django 4.1.3 on 2023-03-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0003_datadiscriptionn_delete_datadiscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDiscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.DeleteModel(
            name='DataDiscriptionN',
        ),
    ]
